# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Muyulong's Blog
subtitle: 今日事，今日毕
description: Just write something...
keywords:
author: muyulong
language: zh-CN
timezone:

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://mmyyll.ml/
permalink: posts/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# abbrlink
abbrlink:  
  alg: crc32
  rep: hex   

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: butterfly

search:
  path: search.xml
  field: post
  content: true

baidu_url_submit:
  count: 1000
  ## 比如3，代表提交最新的三个链接
  host: mmyyll.ml
  ## 在百度站长平台中注册的域名
  token: L3ryHST1Mdnrhkgo
  ## 请注意这是您的秘钥， 请不要发布在公众仓库里!
  path: baidu_urls.txt
  ## 文本文档的地址， 新链接会保存在此文本文档里

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
- type: git
  repo: 
    # github: git@github.com:honjun/honjun.github.io.git
    github: https://github.com/muyulong/muyulong.github.io.git
    # coding: https://e.coding.net/muyulong-01/muyulong.coding.me.git
  branch: master
- type: baidu_url_submitter 
# 百度
#- type: baidu_xz_url_submitter # 百度熊掌号
# backup
backup:
  type: git
  message: backup my blog of https://muyulong.github.io/
  repository:
    github: https://github.com/muyulong/muyulong.github.io.git,backup
    # coding: https://e.coding.net/muyulong-01/muyulong.coding.me.git,backup

server:
  port: 4000
  compress: true
  header: true
  
#RSS
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date


# 自动生成sitemap
sitemap:
    path: sitemap.xml
baidusitemap:
    path: baidusitemap.xml

# index2 generator是否包含官方的hexo-generator-index，默认true（包含）
index2_include_index: true # defult is true

# 配置index2 generator，可以是数组或对象
index2_generator:
  per_page: 10
  order_by: -date
 # include:
 #   - category Web # 只包含Web分类下的文章
  exclude:
    - tag hide # 不包含标签为hide的文章
    - category hide # 不包含分类为hide的文章

# lazyload
#lazyload:
#  enable: false
#  onlypost: false
#  loadingImg: # eg. ./images/loading.png
 
kramed:
  smartypants: false
# hexo-neat
# md博文压缩
neat_enable: true
# 压缩html（ejs，swig等也属于html格式片段）
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '*.min.css'
    - '**/*.min.css'
    - 'jquery.fancybox.min.css'
    - '**/live2d-widget/waifu.css'
    - '**/style.css'
# 压缩js
neat_js:
  enable: true
  mangle: true 
  #打印日志
  output:
  compress:
  exclude: #排除文件
    - '*.min.js'
    - '**/*.min.js'
    - 'jquery.fancybox.min.js'
    - '**/live2d-widget/*.js'
    - '**/live2d-widget/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'  
    - '**/love.js'
    - '**/photo.js'